name: Build
on:
  push:
    branches:
      - master # or the name of your main branch
      - main # or the name of your main branch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - name: Get gometalinter
        run: go get -u gopkg.in/alecthomas/gometalinter.v2 && $GOPATH/bin/gometalinter.v2 --install
      - name: Run gometalinter
        run: $GOPATH/bin/gometalinter.v2 . > gometalinter-report.out || true
      - name: Run test coverage
        run:  go test ./... -coverprofile=coverage.out
      - name: Run test report
        run:  go test ./... -json > report.json
      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      # If you wish to fail your job when the Quality Gate is red, uncomment the
      # following lines. This would typically be used to fail a deployment.
      # - uses: sonarsource/sonarqube-quality-gate-action@master
      #   timeout-minutes: 5
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
