# workflow name
name: Generate release-artifacts

# on events
on:
  push:
    tags: 
        - '*'
env:
  PACKAGE_NAME: gitops-release-manager
# workflow tasks
#https://trstringer.com/github-actions-create-release-upload-artifacts/
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
          check-latest: true
      - name: version
        run: echo "::set-output name=version::$(git describe --tags --always --abbrev=0 --match='[0-9]*.[0-9]*.[0-9]*' 2> /dev/null)"
        id: version
      - name: Run Linux Build
        run: go build -ldflags="-X '${{ env.PACKAGE_NAME }}/pkg/cmd.tversion=${{ steps.version.outputs.version }}'" .
      - name: Run Windows Build
        run: env GOOS=windows GOARCH=amd64 go build -ldflags="-X '${{ env.PACKAGE_NAME }}/pkg/cmd.tversion=${{ steps.version.outputs.version }}'" -o ./${{ env.PACKAGE_NAME }}.exe .
      - name: Run Mac Build
        run: env GOOS=darwin GOARCH=arm64 go build -ldflags="-X '${{ env.PACKAGE_NAME }}/pkg/cmd.tversion=${{ steps.version.outputs.version }}'" -o ./${{ env.PACKAGE_NAME }}_darwin .
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: ./.github/workflows/CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.PACKAGE_NAME }}
          asset_name: ${{ env.PACKAGE_NAME }}
          asset_content_type: text/plain
      - name: upload Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.PACKAGE_NAME }}.exe
          asset_name: ${{ env.PACKAGE_NAME }}.exe
          asset_content_type: text/plain
      - name: upload Mac artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ env.PACKAGE_NAME }}_darwin
          asset_name: ${{ env.PACKAGE_NAME }}_darwin-arm64
          asset_content_type: text/plain